export interface CoffeeI {
  id: number;
  title: string;
  description: string;
  smallImage: string;
  bigImage: string;
  price: number;
  rating: number; // 1 to 5
  reviewCount: number;
  available: boolean;
  origin: string;
  size: string;
  category: string;
  options: string[];
  preparationTime: string;
  ingredients: string[];
  pairing: string;
  servingTemperature: string;
  discount: number; // percentage
}

const getCoffeeList = (): CoffeeI[] => [
  {
    id: 6,
    title: "Irish Coffee",
    description:
      "A warm blend of coffee, Irish whiskey, sugar, and cream, delivering a comforting, boozy treat.",
    smallImage: "/images/small/irish.png",
    bigImage: "/images/big/irish.png",
    price: 18.0,
    rating: 4.8,
    reviewCount: 215,
    available: true,
    origin: "Ireland",
    size: "250ml",
    category: "Alcoholic",
    options: ["Extra cream", "Double whiskey"],
    preparationTime: "5 minutes",
    ingredients: ["Coffee", "Irish whiskey", "Sugar", "Cream"],
    pairing: "Chocolate cake",
    servingTemperature: "Hot",
    discount: 10,
  },
  {
    id: 7,
    title: "Latte",
    description:
      "A creamy coffee made with espresso and steamed milk, offering a mild, rich flavor with a velvety texture.",
    smallImage: "/images/small/latte.png",
    bigImage: "/images/big/latte.png",
    price: 10.0,
    rating: 4.6,
    reviewCount: 130,
    available: true,
    origin: "Italy",
    size: "350ml",
    category: "Espresso",
    options: ["Almond milk", "Soy milk"],
    preparationTime: "3 minutes",
    ingredients: ["Espresso", "Steamed milk"],
    pairing: "Croissant",
    servingTemperature: "Hot",
    discount: 5,
  },
  {
    id: 8,
    title: "Macchiato",
    description:
      "An espresso 'stained' with a small amount of foamed milk, providing a concentrated coffee flavor with a hint of creaminess.",
    smallImage: "/images/small/macchiato.png",
    bigImage: "/images/big/macchiato.png",
    price: 9.5,
    rating: 4.7,
    reviewCount: 105,
    available: true,
    origin: "Italy",
    size: "150ml",
    category: "Espresso",
    options: ["Vanilla syrup", "Caramel drizzle"],
    preparationTime: "2 minutes",
    ingredients: ["Espresso", "Foamed milk"],
    pairing: "Shortbread cookies",
    servingTemperature: "Hot",
    discount: 0,
  },
  {
    id: 1,
    title: "Amaretto Coffee",
    description:
      "A rich, almond-flavored coffee made with a splash of amaretto liqueur for a sweet and nutty kick.",
    smallImage: "/images/small/amaretto.png",
    bigImage: "/images/big/amaretto.png",
    price: 12.5,
    rating: 4.9,
    reviewCount: 180,
    available: true,
    origin: "Italy",
    size: "250ml",
    category: "Alcoholic",
    options: ["Extra amaretto", "Whipped cream"],
    preparationTime: "4 minutes",
    ingredients: ["Coffee", "Amaretto liqueur"],
    pairing: "Biscotti",
    servingTemperature: "Hot",
    discount: 8,
  },
  {
    id: 2,
    title: "Americano",
    description:
      "A simple, strong coffee made by diluting an espresso shot with hot water, creating a light, yet bold flavor.",
    smallImage: "/images/small/americano.png",
    bigImage: "/images/big/americano.png",
    price: 8.0,
    rating: 4.5,
    reviewCount: 140,
    available: true,
    origin: "USA",
    size: "300ml",
    category: "Espresso",
    options: ["Extra shot", "Iced"],
    preparationTime: "2 minutes",
    ingredients: ["Espresso", "Water"],
    pairing: "Bagel",
    servingTemperature: "Hot",
    discount: 0,
  },
  {
    id: 3,
    title: "Cocktail Coffee",
    description:
      "A coffee-based drink combined with alcohol, often served cold or with a mix of syrups, perfect for social occasions.",
    smallImage: "/images/small/cocktail.png",
    bigImage: "/images/big/cocktail.png",
    price: 15.0,
    rating: 4.7,
    reviewCount: 95,
    available: true,
    origin: "Global",
    size: "250ml",
    category: "Alcoholic",
    options: ["Kahlua", "Baileys"],
    preparationTime: "4 minutes",
    ingredients: ["Coffee", "Alcohol"],
    pairing: "Cheesecake",
    servingTemperature: "Cold",
    discount: 12,
  },
  {
    id: 4,
    title: "Glace Coffee",
    description:
      "A coffee served over ice cream, typically a strong espresso poured over a scoop of vanilla or coffee-flavored ice cream.",
    smallImage: "/images/small/glace.png",
    bigImage: "/images/big/glace.png",
    price: 10.5,
    rating: 4.8,
    reviewCount: 85,
    available: true,
    origin: "France",
    size: "200ml",
    category: "Dessert Coffee",
    options: ["Extra ice cream", "Caramel sauce"],
    preparationTime: "3 minutes",
    ingredients: ["Espresso", "Ice cream"],
    pairing: "Brownie",
    servingTemperature: "Cold",
    discount: 0,
  },
  {
    id: 5,
    title: "Iced Coffee",
    description:
      "A refreshing, chilled coffee brewed hot and served cold, often sweetened or with milk for a smooth finish.",
    smallImage: "/images/small/iced.png",
    bigImage: "/images/big/iced.png",
    price: 9.0,
    rating: 4.4,
    reviewCount: 110,
    available: true,
    origin: "USA",
    size: "400ml",
    category: "Iced",
    options: ["Sweetened", "With milk"],
    preparationTime: "3 minutes",
    ingredients: ["Coffee", "Ice", "Milk"],
    pairing: "Donut",
    servingTemperature: "Cold",
    discount: 0,
  },
  {
    id: 9,
    title: "Mocha",
    description:
      "A delightful mix of espresso, steamed milk, and chocolate syrup, topped with whipped cream for a dessert-like coffee experience.",
    smallImage: "/images/small/mocha.png",
    bigImage: "/images/big/mocha.png",
    price: 11.0,
    rating: 4.6,
    reviewCount: 170,
    available: true,
    origin: "Italy",
    size: "350ml",
    category: "Dessert Coffee",
    options: ["Extra chocolate", "Cinnamon"],
    preparationTime: "4 minutes",
    ingredients: [
      "Espresso",
      "Steamed milk",
      "Chocolate syrup",
      "Whipped cream",
    ],
    pairing: "Chocolate croissant",
    servingTemperature: "Hot",
    discount: 5,
  },
  {
    id: 10,
    title: "Caffè con Panna",
    description:
      "An espresso topped with a dollop of whipped cream, adding sweetness and texture to the strong coffee flavor.",
    smallImage: "/images/small/panna.png",
    bigImage: "/images/big/panna.png",
    price: 8.5,
    rating: 4.5,
    reviewCount: 90,
    available: true,
    origin: "Italy",
    size: "150ml",
    category: "Espresso",
    options: ["Extra whipped cream"],
    preparationTime: "2 minutes",
    ingredients: ["Espresso", "Whipped cream"],
    pairing: "Pecan pie",
    servingTemperature: "Hot",
    discount: 0,
  },
  {
    id: 11,
    title: "Caffè Romano",
    description:
      "A bold espresso served with a slice of lemon, giving the coffee a citrusy, zesty twist.",
    smallImage: "/images/small/romano.png",
    bigImage: "/images/big/romano.png",
    price: 7.5,
    rating: 4.2,
    reviewCount: 75,
    available: true,
    origin: "Italy",
    size: "150ml",
    category: "Espresso",
    options: ["Extra lemon"],
    preparationTime: "2 minutes",
    ingredients: ["Espresso", "Lemon"],
    pairing: "Lemon tart",
    servingTemperature: "Hot",
    discount: 0,
  },
  {
    id: 12,
    title: "Venetian Coffee",
    description:
      "A unique coffee blend often infused with spices and sometimes served with a hint of citrus for a sophisticated taste.",
    smallImage: "/images/small/venetian.png",
    bigImage: "/images/big/venetian.png",
    price: 14.0,
    rating: 4.9,
    reviewCount: 65,
    available: true,
    origin: "Italy",
    size: "250ml",
    category: "Spiced Coffee",
    options: ["Extra spices", "Whipped cream"],
    preparationTime: "5 minutes",
    ingredients: ["Coffee", "Spices"],
    pairing: "Gingerbread cookies",
    servingTemperature: "Hot",
    discount: 10,
  },
];

export default getCoffeeList;
